name: Deploy Package

on:
  push:
    tags:
      - v*.*.*

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write

    steps:
      - name: Clone Source Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn && yarn add -D npm-cli-login
      - name: Run Test
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
        run: |
          yarn test:cicd
      - name: Build Package
        run: |
          yarn build
      - name: Publish Package
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public --provenance